# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
  - job: tests_parallel_ci
    strategy:
      parallel: 2

    steps:
    - pwsh:  |
        Write-Host SYSTEM_TOTALJOBSINPHASE = $env:SYSTEM_TOTALJOBSINPHASE
        Write-Host SYSTEM_JOBPOSITIONINPHASE = $env:SYSTEM_JOBPOSITIONINPHASE
      displayName: 'Show environment variables'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
      displayName: 'Use Python 3.9'

    - script: |
        python -m pip install --upgrade pip
        pip install tox
      displayName: 'Install dependencies'

    - script: tox -e ci
      displayName: 'tox -e ci'

  - job: tests_python
    pool:
      vmImage: ubuntu-latest

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
          toxenv: 'py36'
        Python37:
          python.version: '3.7'
          toxenv: 'py37'
        Python38:
          python.version: '3.8'
          toxenv: 'py38'
        Python39:
          python.version: '3.9'
          toxenv: 'py39'
        Python310:
          python.version: '3.10'
          toxenv: 'py310'
        flake8:
          python.version: '3.9'
          toxenv: 'flake8'

    steps:
    - pwsh:  |
        Write-Host SYSTEM_TOTALJOBSINPHASE = $env:SYSTEM_TOTALJOBSINPHASE
        Write-Host SYSTEM_JOBPOSITIONINPHASE = $env:SYSTEM_JOBPOSITIONINPHASE
      displayName: 'Show environment variables'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install tox
      displayName: 'Install dependencies'

    - script: tox -e $(toxenv)
      displayName: 'tox -e $(toxenv)'

    - script: tox -e not-ci
      displayName: 'tox -e not-ci (simulates ci not active)'
